"""Update User table for Google Auth

Revision ID: a5c82040891b
Revises: 5e6df3613d2e
Create Date: 2026-03-30 22:39:00.699076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c82040891b'
down_revision: Union[str, Sequence[str], None] = '5e6df3613d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###
